Refactor deploy-terraservice action into 3 separate actions for deploying env/platform services

diff --git a/.github/actions/bfd-setup-tofu/action.yml b/.github/actions/bfd-setup-tofu/action.yml
--- a/.github/actions/bfd-setup-tofu/action.yml
+++ b/.github/actions/bfd-setup-tofu/action.yml
@@ -1,20 +1,20 @@
-name: "Deploy Terraservice"
-description: "Composite action to deploy a given Terraservice"
+name: "Setup OpenTofu"
+description: >-
+  Composite action to setup OpenTofu such that it can be used on a runner and logging can be sent to
+  CloudWatch
 inputs:
-  bfd-env:
-    description: "The BFD environment to deploy the given service to"
-    required: true
   service-path:
     description: "The path to the Terraservice relative to the root of the repository"
     required: true
   cw-log-group:
-    description: "Name of CloudWatch Log Group to submit Terraform logs to; must exist"
+    description: >-
+      Name of CloudWatch Log Group to submit OpenTofu logs to; will be created if necessary
     required: true
   cw-log-stream:
     description: >-
-      Name of CloudWatch Log Stream to submit Terraform logs to; will be created if necessary
+      Name of CloudWatch Log Stream to submit OpenTofu logs to; will be created if necessary
     required: true
-  terraform-vars-json:
+  tofu-vars-json:
     description: "JSON object map of variables to their values"
     required: false
     default: "{}"
@@ -39,33 +39,38 @@ runs:
             "checked-out?"
           exit 1
         fi
-        # See https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_CreateLogStream.html
-        echo "${{ inputs.cw-log-stream }}" | grep -Pv '[:*]'
+      shell: bash
 
-        is_valid_log_group="$(
-          aws logs describe-log-groups --log-group-name-pattern "${{ inputs.cw-log-group }}" |
-            jq -r '.logGroups != []'
+    - name: Create Log Group if needed
+      run: |
+        # Attempt to create the Log Group, swallowing any error code that is returned and also
+        # capture the stderr output so that it can be checked
+        create_log_group_stderr="$(
+          aws logs create-log-group \
+            --log-group-name "${{ inputs.cw-log-group }}" 2>&1 >/dev/null || true
         )"
-        if [[ $is_valid_log_group == "false" ]]; then
-          echo "'${{ inputs.cw-log-group }}' does not exist; was the the correct Log Group" \
-            "specified?"
+
+        # If there was an error message logged by create-log-group and that error was not
+        # indicating that the Log Group already exists (which is fine), then log that there was an
+        # unrecoverable error and exit
+        if [[
+          -n $create_log_group_stderr &&
+          $create_log_group_stderr != *"ResourceAlreadyExistsException"* ]] \
+          ; then
+          echo "Unrecoverable error occurred when trying to create Log Group" \
+            "'${{inputs.cw-log-stream }}' in Log Group '${{ inputs.cw-log-group }}'"
+          echo "$create_log_group_stderr"
           exit 1
         fi
       shell: bash
 
     - name: Create Log Stream if needed
       run: |
-        # While the Log Group provided in the inputs is assumed to exist already, the Log Stream is
-        # not. Attempt to create it, swallowing any error code that is returned and also capture
-        # the stderr output so that it can be checked
         create_log_stream_stderr="$(
           aws logs create-log-stream --log-group-name "${{ inputs.cw-log-group }}" \
             --log-stream-name "${{ inputs.cw-log-stream }}" 2>&1 >/dev/null || true
         )"
 
-        # If there was an error message logged by create-log-stream and that error was not
-        # indicating that the Log Stream already exists (which is fine), then log that there was an
-        # unrecoverable error and exit
         if [[
           -n $create_log_stream_stderr &&
           $create_log_stream_stderr != *"ResourceAlreadyExistsException"* ]] \
@@ -78,7 +83,7 @@ runs:
 
         echo "'${{inputs.cw-log-stream }}' in Log Group '${{ inputs.cw-log-group }}'" \
           "created or exists already"
-        echo "Tail the Log Stream to view Terraform output in realtime:"
+        echo "Tail the Log Stream to view OpenTofu output in realtime:"
         echo "aws logs tail --since 1h --follow '${{ inputs.cw-log-group }}'"
       shell: bash
 
@@ -88,13 +93,13 @@ runs:
     #   "var2": 123,
     #   "var3": true
     # }
-    # into a space-delimited argument list that the Terraform CLI understands:
+    # into a space-delimited argument list that the OpenTofu CLI understands:
     # -var=var1=val1 -var=var2=123 -var=var3=true
-    - name: Generate Terraform vars args
+    - name: Generate OpenTofu vars args
       id: gen-tf-vars-args
       run: |
         tf_vars_args="$(
-          echo "${{ inputs.terraform-vars-json }}" | jq -r 'to_entries |
+          echo "${{ inputs.tofu-vars-json }}" | jq -r 'to_entries |
             map(select(.value != null and .value != "")) |
             map("\"-var=" + .key + "=" + (.value | tostring)+ "\"") |
             join(" ")'
@@ -132,46 +137,6 @@ runs:
       shell: bash
 
     - name: Setup OpenTofu
-      uses: opentofu/setup-opentofu@4a98c1282d7d0763055637165e94b063d2348721
+      uses: opentofu/setup-opentofu@592200bd4b9bbf4772ace78f887668b1aee8f716 # v1.0.5
       with:
         tofu_version: ${{ steps.get-opentofu-version.outputs.tofu-version }}
-
-    - name: Terraform init
-      run: |
-        cd "${{ github.workspace }}/${{ inputs.service-path }}"
-        tofu --version
-        tofu init -no-color
-      shell: bash
-
-    - name: Select Terraform workspace
-      run: |
-        cd "${{ github.workspace }}/${{ inputs.service-path }}"
-        tofu workspace new "${{ inputs.bfd-env }}" 2> /dev/null || true &&\
-        tertofu workspace select "${{ inputs.bfd-env }}" -no-color
-      shell: bash
-
-    - name: Generate Terraform plan
-      run: |
-        cd "${{ github.workspace }}/${{ inputs.service-path }}"
-
-        # Often the terraform plan logged to stdout as well as the errors logged to stderr include
-        # sensitive/private information. GHA logs are available for anyone logged in with a GitHub
-        # account to view, and so this information must be protected. Instead of logging to stdout,
-        # all potentially sensitive Terraform log output is instead logged to CloudWatch
-        echo "Generating Terraform plan for ${{ inputs.service-path }}..." |
-          tee >(bash -c "$STDOUT_TO_CWLOGS_SCRIPT") # Log to GHA logs and CW
-        tofu plan ${{ steps.gen-tf-vars-args.outputs.tf-vars-args }} -no-color \
-          -out=tfplan 2>&1 | "$STDOUT_TO_CWLOGS_SCRIPT"
-        echo "Plan generated for ${{ inputs.service-path }} successfully" |
-          tee >(bash -c "$STDOUT_TO_CWLOGS_SCRIPT")
-      shell: bash
-
-    - name: Apply Terraservice
-      run: |
-        cd "${{ github.workspace }}/${{ inputs.service-path }}"
-        echo "Applying Terraform plan for ${{ inputs.service-path }}..." |
-          tee >(bash -c "$STDOUT_TO_CWLOGS_SCRIPT")
-        tofu apply -no-color -input=false tfplan 2>&1 | "$STDOUT_TO_CWLOGS_SCRIPT"
-        echo "Terraform plan for ${{ inputs.service-path }} applied" |
-          tee >(bash -c "$STDOUT_TO_CWLOGS_SCRIPT")
-      shell: bash
