Enable IAM RDS auth for bfd server

diff --git a/ops/ansible/roles/bfd-server/templates/bfd-server.sh.j2 b/ops/ansible/roles/bfd-server/templates/bfd-server.sh.j2
--- a/ops/ansible/roles/bfd-server/templates/bfd-server.sh.j2
+++ b/ops/ansible/roles/bfd-server/templates/bfd-server.sh.j2
@@ -1,4 +1,5 @@
 #!/bin/bash
+metadata_token_ttl_seconds=300
 
 # The launcher picks up its config from environment variables, so set those.
 export BFD_PORT='{{ data_server_appserver_https_port }}'
@@ -10,12 +11,30 @@ export BFD_WAR='{{ data_server_dir }}/{{ data_server_war | basename }}'
 # those.
 LOGS_DIR='{{ data_server_dir }}/'
 DB_URL='{{ data_server_db_url }}'
-DB_USERNAME='{{ data_server_db_username }}'
-DB_PASSWORD='{{ data_server_db_password }}'
+DB_HOST="${DB_HOST:-{{ data_server_db_host }}}"
+DB_USERNAME="${DB_USERNAME:-{{ data_server_db_username }}}"
+DB_PASSWORD="${DB_PASSWORD:-{{ data_server_db_password }}}"
 DB_CONNECTIONS_MAX='{{ data_server_db_connections_max }}'
 BFD_PAC_ENABLED='{{ pac_resources_enabled }}'
 BFD_PAC_CLAIM_SOURCE_TYPES='{{ pac_claim_source_types }}'
 
+# If DB_USERNAME or DB_PASSWORD was not set, use IAM for db auth
+if  [ -z "$DB_USERNAME" ] || [ -z "$DB_PASSWORD" ]; then
+  # Get the instance profile role name from the metadata service. This is the database username.
+  log "Retrieving RDS IAM authentication token for {{ data_server_db_host }}"
+  IMDSv2_TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: $metadata_token_ttl_seconds")
+  DB_USERNAME=$(curl -s -S -H "X-aws-ec2-metadata-token: $IMDSv2_TOKEN" http://169.254.169.254/latest/meta-data/iam/security-credentials/)
+  for i in {1..3}; do
+    if ! DB_PASSWORD="$(aws rds generate-db-auth-token --hostname "$DB_HOST" --port 5432 --username="$DB_USERNAME")"; then
+      log "Failed to obtain rds auth token for $DB_HOST retrying... (attempt $i/3)"
+      sleep 1
+    fi
+  done
+  if [[ -z "$DB_PASSWORD" ]]; then
+    log "Failed to obtain an auth token for $DB_HOST after 3 attempts, exiting..."
+    exit 1
+  fi
+fi
 # The New Relic agent running in the WAR needs some additional environment variables, so set those.
 {% if data_server_new_relic_license_key is defined %}
 export NEW_RELIC_HOST='gov-collector.newrelic.com'
@@ -138,6 +157,7 @@ service_startup_check() {
 
 # Set some additional variables.
 JVM_ARGS='{{ data_server_appserver_jvmargs }}'
+
 
 # 3... 2... 1... launch!
 bfd-server-launcher-1.0.0-SNAPSHOT/bfd-server-launcher.sh \
