BLUEBUTTON-1271: Startup smoke testing; Jetty edition (#83)
* Initial port of smoke testing from Jboss to Jetty

* Namespace all variables, find new Jetty PID

* Quote all the things, comment blocks, actually kick off tests

* Actually run in the background

* Fix logic error

* Add better date handling and cloudwatch log ingest for startup testing

* Incorporate fixes suggested by @karlmdavis

* Extra pipe failure protection

* Remove feature toggle for smoke testing

* Add more specific logging

diff --git a/ops/ansible/roles/bfd-server/templates/bfd-server.sh.j2 b/ops/ansible/roles/bfd-server/templates/bfd-server.sh.j2
--- a/ops/ansible/roles/bfd-server/templates/bfd-server.sh.j2
+++ b/ops/ansible/roles/bfd-server/templates/bfd-server.sh.j2
@@ -33,6 +33,75 @@ export NEW_RELIC_ENVIRONMENT='{{ data_server_new_relic_environment }}'
 {% endif %}
 {% endif %}
 
+# Begin smoke testing startup routine
+STARTUP_TESTING_RETRIES='3'
+STARTUP_TESTING_BOOT_TIMEOUT='30'
+STARTUP_TESTING_REQ_TIMEOUT='15'
+STARTUP_TESTING_REQ_BACKOFF_TIMEOUT='10'
+STARTUP_TESTING_BENE_ID='-201'
+
+##
+# Prints out the specified message.
+#
+# Params:
+# * $1: the message to log
+##
+log() {
+  echo "$(date +%F\ %T): $1"
+}
+
+##
+# Verifies that the specified endpoint/query can be queried via curl without error and produced the expected output.
+#
+# Params:
+# * $1: the full URL to query via curl
+# * $2: the value to confirm is present in the curl output; if not found, then the query should be regarded as unsuccessful
+##
+check_endpoint() {
+  set -o pipefail
+  curl --max-time $STARTUP_TESTING_REQ_TIMEOUT --silent --insecure --cert-type pem --cert "{{ data_server_dir }}/bluebutton-backend-test-data-server-client-test-keypair.pem" "$1" | grep "$2"
+}
+
+##
+# Runs test queries to verify that the server is working as expected. If not, issues a 'kill -INT' on the server's process to shut it down.
+##
+stop_service_if_failing() {
+  log "Waiting $STARTUP_TESTING_BOOT_TIMEOUT seconds for initial startup"
+  sleep $STARTUP_TESTING_BOOT_TIMEOUT
+
+  for I in $(seq $STARTUP_TESTING_RETRIES); do
+    log "Checking metadata endpoint"
+    STARTUP_TESTING_CHECK_METADATA=$(check_endpoint "https://localhost:7443/v1/fhir/metadata?_format=application%2Fjson%2Bfhir" "status")
+    STARTUP_TESTING_CHECK_METADATA_EXIT=$?
+
+    log "Checking coverage resource endpoint for bene $STARTUP_TESTING_BENE_ID"
+    STARTUP_TESTING_CHECK_DATABASE=$(check_endpoint "https://localhost:7443/v1/fhir/Coverage?beneficiary=$STARTUP_TESTING_BENE_ID&_format=application%2Fjson%2Bfhir" "id")
+    STARTUP_TESTING_CHECK_DATABASE_EXIT=$?
+
+    if [[ $STARTUP_TESTING_CHECK_METADATA_EXIT == 0 ]] && [[ $STARTUP_TESTING_CHECK_DATABASE_EXIT == 0 ]]; then
+      log "Server started properly"
+      return 0
+    elif [[ $I -lt $STARTUP_TESTING_RETRIES ]]; then
+      log "Server failed to start properly, backing off"
+      sleep $STARTUP_TESTING_REQ_BACKOFF_TIMEOUT
+    fi
+  done
+
+  log "Server failed to start properly, shutting down"
+  STARTUP_TESTING_BFD_PID=$(ps -ef | grep 'DataServerLauncherApp' | grep -v grep | awk '{print $2}')
+  STARTUP_TESTING_BFD_PID_EXIT=$?
+
+  if [[ $STARTUP_TESTING_BFD_PID_EXIT == 0 ]] && kill -INT $STARTUP_TESTING_BFD_PID; then
+    log "Server shut down gracefully"
+  else
+    log "Error shutting down server gracefully"
+  fi
+  return 1
+}
+
+(stop_service_if_failing >>"{{ data_server_dir }}/bfd-server-startup.log" 2>&1) &
+# End smoke testing startup routine
+
 # Set some additional variables.
 JVM_ARGS='{{ data_server_appserver_jvmargs }}'
 
