error handeling

diff --git a/ops/ansible/roles/bfd-pipeline/templates/bfd-pipeline-service.sh.j2 b/ops/ansible/roles/bfd-pipeline/templates/bfd-pipeline-service.sh.j2
--- a/ops/ansible/roles/bfd-pipeline/templates/bfd-pipeline-service.sh.j2
+++ b/ops/ansible/roles/bfd-pipeline/templates/bfd-pipeline-service.sh.j2
@@ -16,6 +16,7 @@ DATABASE_URL="${DATABASE_URL:-"{{ data_pipeline_db_url }}"}"
 DATABASE_USERNAME="${DATABASE_USERNAME:-{{ data_pipeline_db_username }}}"
 DATABASE_PASSWORD="${DATABASE_PASSWORD:-{{ data_pipeline_db_password }}}"
 
+
 # If DATABASE_USERNAME and DATABASE_PASSWORD is set to "iam", we are using iam for authentication. The username and password will be
 # replaced with the actual values from the metadata service and the generate-db-auth-token command.
 if [[ "$DATABASE_USERNAME" == "iam" && "$DATABASE_PASSWORD" == "iam" ]]; then
@@ -26,14 +27,20 @@ if [[ "$DATABASE_USERNAME" == "iam" && "$DATABASE_PASSWORD" == "iam" ]]; then
 
   # Get the instance profile role from the metadata service. This is the database username.
   log "Retrieving auth token for $DATABASE_HOST"
-  IMDSv2_TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: $metadata_token_ttl_seconds")
-  DATABASE_USERNAME=$(curl -s -S -H "X-aws-ec2-metadata-token: $IMDSv2_TOKEN" http://169.254.169.254/latest/meta-data/iam/security-credentials/)
+  if ! IMDSv2_TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: $metadata_token_ttl_seconds"); then
+    log "Failed to retrieve IMDSv2 token from the AWS metadata service... Is this an EC2 instance?"
+    exit 1
+  fi
+  if ! DATABASE_USERNAME=$(curl -s -S -H "X-aws-ec2-metadata-token: $IMDSv2_TOKEN" http://169.254.169.254/latest/meta-data/iam/security-credentials/); then
+    log "Failed to retrieve instance profile role from the AWS metadata service... Is this an EC2 instance?"
+    exit 1
+  fi
   for i in {1..3}; do
     if DATABASE_PASSWORD="$(aws rds generate-db-auth-token --hostname "$DATABASE_HOST" --port 5432 --username="$DATABASE_USERNAME")"; then
       log "OK"
       break
     else
-      log "Failed to token for $DATABASE_HOST retrying... (attempt $i/3)"
+      log "Failed to obtain token for $DATABASE_HOST retrying... (attempt $i/3)"
       sleep 1
     fi
   done
diff --git a/ops/ansible/roles/bfd-server/templates/bfd-server.sh.j2 b/ops/ansible/roles/bfd-server/templates/bfd-server.sh.j2
--- a/ops/ansible/roles/bfd-server/templates/bfd-server.sh.j2
+++ b/ops/ansible/roles/bfd-server/templates/bfd-server.sh.j2
@@ -21,15 +21,21 @@ DB_CONNECTIONS_MAX="${DB_CONNECTIONS_MAX:-'{{ data_server_db_connections_max }}'
 # If DB_USERNAME and DB_PASSWORD is set to "iam", we are using iam for authentication. The username and password will be
 # replaced with the actual values from the metadata service and the generate-db-auth-token command.
 if [[ "$DB_USERNAME" == "iam" && "$DB_PASSWORD" == "iam" ]]; then
-  log "Using IAM authentication for database connection"
+  log "IAM authentication enabled for database connection"
 
   # Get the hostname from the DB_URL.
   DB_HOST=$(echo "$DB_URL" | sed -n 's/.*\/\/\(.*\):.*/\1/p')
 
   # Get the instance profile role from the metadata service. This is the database username.
-  log "Retrieving authentication token for $DB_HOST"
-  IMDSv2_TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: $metadata_token_ttl_seconds")
-  DB_USERNAME=$(curl -s -S -H "X-aws-ec2-metadata-token: $IMDSv2_TOKEN" http://169.254.169.254/latest/meta-data/iam/security-credentials/)
+  log "Retrieving auth token for $DB_HOST"
+  if ! IMDSv2_TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: $metadata_token_ttl_seconds"); then
+    log "Failed to retrieve IMDSv2 token from the AWS metadata service... Is this an EC2 instance?"
+    exit 1
+  fi
+  if ! DB_USERNAME=$(curl -s -S -H "X-aws-ec2-metadata-token: $IMDSv2_TOKEN" http://169.254.169.254/latest/meta-data/iam/security-credentials/); then
+    log "Failed to retrieve instance profile role from the AWS metadata service... Is this an EC2 instance?"
+    exit 1
+  fi
   for i in {1..3}; do
     if DB_PASSWORD="$(aws rds generate-db-auth-token --hostname "$DB_HOST" --port 5432 --username="$DB_USERNAME")"; then
       log "OK"
@@ -40,7 +46,7 @@ if [[ "$DB_USERNAME" == "iam" && "$DB_PASSWORD" == "iam" ]]; then
     fi
   done
   if [[ -z "$DB_PASSWORD" ]]; then
-    log "Failed to obtain rds auth token for $DB_HOST after 3 attempts, exiting..."
+    log "Failed to obtain token for $DB_HOST after 3 attempts, exiting..."
     exit 1
   fi
 fi
