finish rds auth for migrator

diff --git a/ops/ansible/roles/bfd-db-migrator/templates/bfd-db-migrator-service.sh.j2 b/ops/ansible/roles/bfd-db-migrator/templates/bfd-db-migrator-service.sh.j2
--- a/ops/ansible/roles/bfd-db-migrator/templates/bfd-db-migrator-service.sh.j2
+++ b/ops/ansible/roles/bfd-db-migrator/templates/bfd-db-migrator-service.sh.j2
@@ -1,23 +1,24 @@
 #!/usr/bin/env bash
-
+metadata_token_ttl_seconds=300
+DATABASE_HOST="${DATABASE_HOST:-{{ db_migrator_db_host }}"
 DATABASE_URL="${DATABASE_URL:-{{ db_migrator_db_url }}}"
 DATABASE_USERNAME="${DATABASE_USERNAME:-{{ db_migrator_db_username }}}"
 DATABASE_PASSWORD="${DATABASE_PASSWORD:-{{ db_migrator_db_password }}}"
 
 # If DATABASE_USERNAME or DATABASE_PASSWORD is not set, use IAM for db auth
-if [[ -z "$DATABASE_USERNAME" || -z "$DATABASE_PASSWORD" ]]; then
+if [ -z "$DATABASE_USERNAME" ] || [ -z "$DATABASE_PASSWORD" ]; then
   # Get the instance profile role from the metadata service. This is the database username.
   log "Retrieving RDS IAM authentication token for {{ data_server_db_host }}"
-  IMDSv2_TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
+  IMDSv2_TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: $metadata_token_ttl_seconds")
   DATABASE_USERNAME=$(curl -s -S -H "X-aws-ec2-metadata-token: $IMDSv2_TOKEN" http://169.254.169.254/latest/meta-data/iam/security-credentials/)
   for i in {1..3}; do
-    if ! DATABASE_PASSWORD="$(aws rds generate-db-auth-token --hostname {{ data_server_db_host }} --port 5432 --username=$DATABASE_USERNAME)"; then
-      log "Failed to obtain rds auth token for {{ data_server_db_host }} retrying... (attempt $i/3)"
+    if ! DATABASE_PASSWORD="$(aws rds generate-db-auth-token --hostname "$DATABASE_HOST" --port 5432 --username="$DATABASE_USERNAME")"; then
+      log "Failed to obtain rds auth token for $DATABASE_HOST retrying... (attempt $i/3)"
       sleep 1
     fi
   done
   if [[ -z "$DATABASE_PASSWORD" ]]; then
-    log "Failed to obtain rds auth token for {{ data_server_db_host }} after 3 attempts, exiting..."
+    log "Failed to obtain rds auth token for $DATABASE_HOST after 3 attempts, exiting..."
     exit 1
   fi
 fi
