Switch to OpenTofu in deploy-terraservice

diff --git a/.github/actions/deploy-terraservice/action.yml b/.github/actions/deploy-terraservice/action.yml
--- a/.github/actions/deploy-terraservice/action.yml
+++ b/.github/actions/deploy-terraservice/action.yml
@@ -102,36 +102,52 @@ runs:
         echo "tf-vars-args=$tf_vars_args" >> $GITHUB_OUTPUT
       shell: bash
 
-    - name: Check if tfvm is installed
-      id: check-tfvm-installed
+    - name: Get OpenTofu Version
+      id: get-opentofu-version
       run: |
-        is_tfvm_installed="$(
-          if [[ -x "$(command -v tfvm)" ]]; then
-            echo "true"
-          else
-            echo "false"
+        cd "${{ github.workspace }}/${{ inputs.service-path }}"
+
+        found_file=""
+        current_dir="$PWD"
+
+        # Walk up the directory tree from current working directory
+        while [[ "$current_dir" != "/" && -z "$found_file" ]]; do
+          if [[ -f "$current_dir/.opentofu-version" ]]; then
+            tofu_version="$(head -n 1 "$current_dir/.opentofu-version")"
+            found_file="$current_dir/.opentofu-version"
           fi
-        )"
-        echo "is-tfvm-installed=$is_tfvm_installed" >> $GITHUB_OUTPUT
+
+          # Move to parent directory
+          current_dir="$(dirname "$current_dir")"
+        done
+
+        if [[ -n "$found_file" ]]; then
+          echo "Found .opentofu-version file at $found_file specifying version: $tofu_version"
+        else
+          echo ".opentofu-version file not found."
+          exit 1
+        fi
+
+        echo "tofu-version=$tofu_version" >> $GITHUB_OUTPUT
       shell: bash
 
-    - name: Setup Terraform
-      # Only install tfvm/Terraform if the current runner does not have tfvm installed
-      if: steps.check-tfvm-installed.outputs.is-tfvm-installed == 'false'
-      uses: cbuschka/setup-tfvm@v1
+    - name: Setup OpenTofu
+      uses: opentofu/setup-opentofu@4a98c1282d7d0763055637165e94b063d2348721
+      with:
+        tofu_version: ${{ steps.get-opentofu-version.outputs.tofu-version }}
 
     - name: Terraform init
       run: |
         cd "${{ github.workspace }}/${{ inputs.service-path }}"
-        terraform --version
-        terraform init -no-color
+        tofu --version
+        tofu init -no-color
       shell: bash
 
     - name: Select Terraform workspace
       run: |
         cd "${{ github.workspace }}/${{ inputs.service-path }}"
-        terraform workspace new "${{ inputs.bfd-env }}" 2> /dev/null || true &&\
-        terraform workspace select "${{ inputs.bfd-env }}" -no-color
+        tofu workspace new "${{ inputs.bfd-env }}" 2> /dev/null || true &&\
+        tertofu workspace select "${{ inputs.bfd-env }}" -no-color
       shell: bash
 
     - name: Generate Terraform plan
@@ -144,7 +160,7 @@ runs:
         # all potentially sensitive Terraform log output is instead logged to CloudWatch
         echo "Generating Terraform plan for ${{ inputs.service-path }}..." |
           tee >(bash -c "$STDOUT_TO_CWLOGS_SCRIPT") # Log to GHA logs and CW
-        terraform plan ${{ steps.gen-tf-vars-args.outputs.tf-vars-args }} -no-color \
+        tofu plan ${{ steps.gen-tf-vars-args.outputs.tf-vars-args }} -no-color \
           -out=tfplan 2>&1 | "$STDOUT_TO_CWLOGS_SCRIPT"
         echo "Plan generated for ${{ inputs.service-path }} successfully" |
           tee >(bash -c "$STDOUT_TO_CWLOGS_SCRIPT")
@@ -155,13 +171,7 @@ runs:
         cd "${{ github.workspace }}/${{ inputs.service-path }}"
         echo "Applying Terraform plan for ${{ inputs.service-path }}..." |
           tee >(bash -c "$STDOUT_TO_CWLOGS_SCRIPT")
-        terraform apply -no-color -input=false tfplan 2>&1 | "$STDOUT_TO_CWLOGS_SCRIPT"
+        tofu apply -no-color -input=false tfplan 2>&1 | "$STDOUT_TO_CWLOGS_SCRIPT"
         echo "Terraform plan for ${{ inputs.service-path }} applied" |
           tee >(bash -c "$STDOUT_TO_CWLOGS_SCRIPT")
       shell: bash
-
-    # Ensures that orphaned, background AWS PutLogEvents invocations from using
-    # "stdout-to-cwlogs.sh" are able to complete before being cleaned-up by GHA
-    - name: Await Terraform CloudWatch logging
-      if: always()
-      uses: ./.github/actions/await-cw-logging
