Immediately upload Terraform logs in realtime using background subshell

diff --git a/.github/actions/deploy-terraservice/action.yml b/.github/actions/deploy-terraservice/action.yml
--- a/.github/actions/deploy-terraservice/action.yml
+++ b/.github/actions/deploy-terraservice/action.yml
@@ -39,14 +39,27 @@ runs:
         fi
       shell: bash
 
-    - name: Get Terraform logs file paths
-      id: tf-logs-file-path
+    - name: Create CloudWatch Log Stream if needed
       run: |
-        uuid="$(uuidgen)"
-        raw_logs_path="${{ github.workspace }}/$uuid.raw.json"
-        echo "raw_logs_path=$raw_logs_path" >> $GITHUB_OUTPUT
-        processed_logs_path="${{ github.workspace }}/$uuid.processed.json"
-        echo "processed_logs_path=$processed_logs_path" >> $GITHUB_OUTPUT
+        # While the Log Group provided in the inputs is assumed to exist already, the Log Stream is
+        # not. Attempt to create it, swallowing any error code that is returned and also capture
+        # the stderr output so that it can be checked
+        create_log_stream_stderr="$(
+          aws logs create-log-stream --log-group-name "${{ inputs.cloudwatchLogGroup }}" \
+            --log-stream-name "${{ inputs.cloudwatchLogStream }}" 2>&1 >/dev/null || true
+        )"
+
+        # If there was an error message logged by create-log-stream and that error was not
+        # indicating that the Log Stream already exists (which is fine), then log that there was an
+        # unrecoverable error and exit
+        if [[ -n $create_log_stream_stderr && $create_log_stream_stderr != *"ResourceAlreadyExistsException"* ]]; then
+          echo "Unrecoverable error occurred when trying to create Log Stream '${{inputs.cloudwatchLogStream }}' in Log Group '${{ inputs.cloudwatchLogGroup }}' ";
+          echo "$create_log_stream_stderr"
+          exit 1
+        fi
+
+        echo "'${{inputs.cloudwatchLogStream }}' in Log Group '${{ inputs.cloudwatchLogGroup }}' created or exists already"
+        echo "Tail the Log Stream to view Terraform output in realtime"
       shell: bash
 
     # Maps a given JSON object string of variable names to values, i.e.:
@@ -103,17 +116,22 @@ runs:
         # sensitive/private information. GHA logs are available for anyone logged in with a GitHub
         # account to view, and so this information must be protected. Instead of logging to stdout,
         # all potentially sensitive Terraform log output is transformed into a format CloudWatch
-        # Logs understands and appended to a temporary file. These logs are then uploaded at the
-        # end of this action, regardless of success or failure
+        # Logs understands and uploaded to CloudWatch Logs via Bash process susbtitution
         echo "Generating Terraform plan for ${{ inputs.servicePath }}..."
         terraform plan ${{ steps.gen-tf-vars-args.outputs.tf_vars_args }} -no-color -out=tfplan &> >(
           while read line; do
-            echo "$(
+            log_event="$(
               jq -n \
                 --arg unix_ts "$(date +%s%3N)" \
                 --arg line "$line" \
-                '{ "timestamp": ($unix_ts | tonumber), "message": ($line | tostring) }'
-            )" >> "${{ steps.tf-logs-file-path.outputs.raw_logs_path }}"
+                '[{ "timestamp": ($unix_ts | tonumber), "message": ($line | tostring) }]'
+            )"
+            # Runs in a background subshell to avoid slowing down the Terraform process while
+            # trying to put the log output to CloudWatch. Errors are ignored and all output is
+            # redirected to /dev/null
+            (aws logs put-log-events --log-group-name "${{ inputs.cloudwatchLogGroup }}" \
+              --log-stream-name "${{ inputs.cloudwatchLogStream }}" \
+              --log-events "$log_event" &>/dev/null || true) &
           done
         )
         echo "Plan generated for ${{ inputs.servicePath }} successfully"
@@ -125,55 +143,17 @@ runs:
     #     cd "${{ github.workspace }}/${{ inputs.servicePath }}"
     #     echo "Applying Terraform plan for ${{ inputs.servicePath }}..."
     #     terraform apply -no-color -input=false tfplan &> >(
-    #       while read line; do
-    #         echo "$(
-    #           jq -n \
-    #             --arg unix_ts "$(date +%s%3N)" \
-    #             --arg line "$line" \
-    #             '{ "timestamp": ($unix_ts | tonumber), "message": ($line | tostring) }'
-    #         )" >> "${{ steps.tf-logs-file-path.outputs.raw_logs_path }}"
-    #       done
+          # while read line; do
+          #   log_event="$(
+          #     jq -n \
+          #       --arg unix_ts "$(date +%s%3N)" \
+          #       --arg line "$line" \
+          #       '[{ "timestamp": ($unix_ts | tonumber), "message": ($line | tostring) }]'
+          #   )"
+          #   (aws logs put-log-events --log-group-name "${{ inputs.cloudwatchLogGroup }}" \
+          #     --log-stream-name "${{ inputs.cloudwatchLogStream }}" \
+          #     --log-events "$log_event" &>/dev/null || true) &
+          # done
     #     )
     #     echo "Terraform plan for ${{ inputs.servicePath }} applied"
     # shell: bash
-
-    # This step uploads the potentially sensitive Terraform log output from previous steps to
-    # CloudWatch Logs so that BFD Engineers can still inspect the output without fear of that
-    # potentially sensitive information being exposed publicly
-    - name: Submit Terraform logs to CloudWatch
-      # Run regardless of prior step outcome
-      if: always()
-      run: |
-        if [[ -z "${{ steps.tf-logs-file-path.outputs.raw_logs_path }}" || ! -f "${{ steps.tf-logs-file-path.outputs.raw_logs_path }}" ]]; then
-          echo "No logs to submit to CloudWatch"
-          exit
-        fi
-
-        # While the Log Group provided in the inputs is assumed to exist already, the Log Stream is
-        # not. Attempt to create it, swallowing any error code that is returned and also capture
-        # the stderr output so that it can be checked
-        create_log_stream_stderr="$(
-          aws logs create-log-stream --log-group-name "${{ inputs.cloudwatchLogGroup }}" \
-            --log-stream-name "${{ inputs.cloudwatchLogStream }}" 2>&1 >/dev/null || true
-        )"
-
-        # If there was an error message logged by create-log-stream and that error was not
-        # indicating that the Log Stream already exists (which is fine), then log that there was an
-        # unrecoverable error and exit
-        if [[ -n $create_log_stream_stderr && $create_log_stream_stderr != *"ResourceAlreadyExistsException"* ]]; then
-          echo "Unrecoverable error occurred when trying to create Log Stream '${{inputs.cloudwatchLogStream }}' in Log Group '${{ inputs.cloudwatchLogGroup }}' ";
-          echo "$create_log_stream_stderr"
-          exit 1
-        fi
-
-        # Process the "raw" JSON logs from each Terraform invocation into an array of non-empty
-        # log events that CloudWatch understands
-        jq -s '. | map(select(.message != ""))' "${{ steps.tf-logs-file-path.outputs.raw_logs_path }}" > \
-          "${{ steps.tf-logs-file-path.outputs.processed_logs_path }}"
-        # Submit the "processed" logs file to CloudWatch. Capture stdout and ignore it
-        aws logs put-log-events --log-group-name "${{ inputs.cloudwatchLogGroup }}" \
-          --log-stream-name "${{ inputs.cloudwatchLogStream }}" \
-          --log-events "file://${{ steps.tf-logs-file-path.outputs.processed_logs_path }}" 1>/dev/null
-
-        echo "Terraform logs put to Log Group '${{ inputs.cloudwatchLogGroup }}' in Log Stream '${{ inputs.cloudwatchLogStream }}'"
-      shell: bash
